### ISSUE TITLE
Bug: not all domains are accurate

### ISSUE THREAD

**Issue by Samathingamajig** [tjrgg/invite-regex#1]
Due to the way the regex is created
```js
const domain = '(?:disco|discord|discordapp).(?:com|gg|io|li|me|net|org)';
```
someone can put, for example,
```none
https://discordapp.li/invite/fwefwefwewfwfw
```
and this doesn't make sense, since `discordapp.li` is not a registered domain

![image](https://user-images.githubusercontent.com/29130894/176611604-303601e6-c14b-4dd2-9a5c-c55dc94d8b16.png)

I'm sure there are other collisions where the domain is not registered, but this is just the first that I thought of.

**Comment by tjrgg** [comment]
I have no interest in fixing this issue, but I'd be open to a PR that updates the RegEx accordingly or adds a check to see if a domain is registered.
